#!/bin/sh
# shellcheck disable=SC2039
# shellcheck disable=SC3048
trap '' SIGHUP

querymode="$(grep "QUERYMODE" /jffs/addons/uiDivStats.d/config | cut -f2 -d"=")"
tailfilesuffix=""
if [ "$querymode" = "A+AAAA" ] || [ "$querymode" = "A+AAAA+HTTPS" ]; then
	tailfilesuffix="-a-aaaa"
fi

tailfile=""
if grep -q "log-queries=extra" /etc/dnsmasq.conf ; then
	tailfile="/jffs/addons/uiDivStats.d/taildns.d/dnsmasqtotalextra$tailfilesuffix.awk"
else
	tailfile="/jffs/addons/uiDivStats.d/taildns.d/dnsmasqtotal$tailfilesuffix.awk"
fi

renice 15 $$

tail -F /opt/var/log/dnsmasq.log /opt/var/log/dnsmasq.log3 | awk -f "$tailfile" | \

while read -r line; do \
timestamp="$(echo "$line" | cut -f1 -d',')" \
srcip="$(echo "$line" | cut -f2 -d',')" \
reqdmn="$(echo "$line" | cut -f3 -d',')" \
qrytype="$(echo "$line" | cut -f4 -d',')" \
allowed="$(echo "$line" | cut -f5 -d',')" \

echo "$timestamp,$srcip,$reqdmn,$qrytype,$allowed" >> /tmp/cache-uiDivStats-SQL.tmp \

done

renice 0 $$
