#!/bin/sh
#shellcheck disable=SC2039
trap '' SIGHUP
tail -F /opt/var/log/dnsmasq.log /opt/var/log/dnsmasq.log3 | /jffs/addons/uiDivStats.d/taildns.d/dnsmasqblocked.awk | \

while read line; do \
timestamp="$(echo $line | cut -f1 -d',')" \
srcip="$(echo $line | cut -f2 -d',')" \
reqdmn="$(echo $line | cut -f3 -d',')" \
reason="$(echo $line | cut -f4 -d',')" \

echo "CREATE TABLE IF NOT EXISTS [dnsqueriesblocked] ([QueryID] INTEGER PRIMARY KEY NOT NULL, [Timestamp] NUMERIC NOT NULL, [SrcIP] NUMERIC NOT NULL, [ReqDmn] TEXT NOT NULL, [Reason] Text NOT NULL); \
INSERT INTO dnsqueriesblocked ([Timestamp],[SrcIP],[ReqDmn],[Reason]) values($timestamp,\"$srcip\",\"$reqdmn\",\"$reason\");" > /opt/share/dnsqueriesblocked.sql \

/opt/bin/sqlite3 "/opt/share/dnsqueries.db" < /opt/share/dnsqueriesblocked.sql ; done
